disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "HenryYang's blog"

[params]
displayName = "HenryYang"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
# logo = "img/logo.png"
# secondaryLogo = "img/secondary-logo.png"
description = "HenryYang's blog"
# copyright = "Copy, _right?_ :thinking_face:"

[params.author]
name = "HenryYang"
email = "yanghgri@gmail.com"
image = "img/blowfish_logo.png"
imageQuality = 96
headline = "A full-stack developer"
bio = ""
links = [
  { email = "mailto:yanghgri@gmail.com" },
  { github = "https://github.com/YangHgRi" },
]
